### PR TITLE
Add Dockerfile for Application Deployment

### PR DESCRIPTION
**Pull request by CurlyBracess**
### Summary
This PR introduces a Dockerfile for the deployment of the Swiggy app, streamlining the development and production workflows.

### Changes Made
- Added a Dockerfile to containerize the application.
- Configured necessary environment variables and dependencies.
- Included instructions for building and running the container.

### Testing
- Built the Docker image using the provided Dockerfile.
- Successfully ran the container and verified that the application functions as expected.

### Next Steps
- Review the Dockerfile and provide feedback.
- Merge to main once approved.

### CODE REVIEW

**Review by Lutfar1996 — COMMENTED** [review]
Hello Curlybracess,

Please use the base image of alpine!!!!

**Comment by CurlyBracess** [comment]
Ok , I changed the base image. Please have a look

**Comment by CurlyBracess** [comment]
I change it NOw

**Review by Lutfar1996 — COMMENTED** [review]
Ok that's great ! ! !

**Comment by CurlyBracess** [comment]
Thank you

**Pull request merged**
